name: tests
on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.8.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest mypy
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        export PYTHONPATH=$PYTHONPATH:/home/runner/work/atla-generator/atla-generator/src
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics # temporary comment for tests
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Check types with mypy
      run: |
        export PYTHONPATH=$PYTHONPATH:/home/runner/work/atla-generator/atla-generator/src
        mypy src/
    - name: Test with pytest
      run: |
        cd tests/
        export PYTHONPATH=$PYTHONPATH:/home/runner/work/atla-generator/atla-generator/src
        pytest
